"""try to fix

Revision ID: 0855b29c67e1
Revises: 82a4d6d7ecae
Create Date: 2022-04-08 23:34:24.145893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0855b29c67e1'
down_revision = '82a4d6d7ecae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
