"""fix

Revision ID: 09b4318098cc
Revises: 0855b29c67e1
Create Date: 2022-04-10 02:06:25.498363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b4318098cc'
down_revision = '0855b29c67e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfume_in_cart', sa.Column('perfume_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'perfume_in_cart', 'perfume', ['perfume_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'perfume_in_cart', type_='foreignkey')
    op.drop_column('perfume_in_cart', 'perfume_id')
    # ### end Alembic commands ###
