"""fix

Revision ID: 15cfb1ed6af4
Revises: 7bf06b029587
Create Date: 2022-04-10 02:07:06.968701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15cfb1ed6af4'
down_revision = '7bf06b029587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
