"""add model

Revision ID: 39af82eaf71e
Revises: be10b547de67
Create Date: 2022-04-13 22:02:17.749203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39af82eaf71e'
down_revision = 'be10b547de67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfume_in_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('perfume_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfume_in_order_id'), 'perfume_in_order', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_perfume_in_order_id'), table_name='perfume_in_order')
    op.drop_table('perfume_in_order')
    # ### end Alembic commands ###
