"""first

Revision ID: 61beb9cc6a9c
Revises: 
Create Date: 2022-04-08 23:12:14.576613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61beb9cc6a9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfume',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('milliliters', sa.Integer(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_perfume_brand'), 'perfume', ['brand'], unique=False)
    op.create_index(op.f('ix_perfume_id'), 'perfume', ['id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('order_counter', sa.Integer(), nullable=True),
    sa.Column('super_user', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_table('cart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_id'), 'cart', ['id'], unique=True)
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('shipped', sa.Boolean(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('tracking_number', sa.String(length=50), nullable=True),
    sa.Column('perfume_ids', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=True)
    op.create_table('perfume_images',
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=False),
    sa.Column('original', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('perfume_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ),
    sa.PrimaryKeyConstraint('width', 'height', 'id')
    )
    op.create_index(op.f('ix_perfume_images_id'), 'perfume_images', ['id'], unique=True)
    op.create_table('perfume_in_cart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfume_in_cart_id'), 'perfume_in_cart', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_perfume_in_cart_id'), table_name='perfume_in_cart')
    op.drop_table('perfume_in_cart')
    op.drop_index(op.f('ix_perfume_images_id'), table_name='perfume_images')
    op.drop_table('perfume_images')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_cart_id'), table_name='cart')
    op.drop_table('cart')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_perfume_id'), table_name='perfume')
    op.drop_index(op.f('ix_perfume_brand'), table_name='perfume')
    op.drop_table('perfume')
    # ### end Alembic commands ###
