"""fix

Revision ID: 7bf06b029587
Revises: 09b4318098cc
Create Date: 2022-04-10 02:06:50.433150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf06b029587'
down_revision = '09b4318098cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
