"""second

Revision ID: 82a4d6d7ecae
Revises: 61beb9cc6a9c
Create Date: 2022-04-08 23:17:50.008060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a4d6d7ecae'
down_revision = '61beb9cc6a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
