"""fix

Revision ID: be10b547de67
Revises: 15cfb1ed6af4
Create Date: 2022-04-10 03:21:36.182754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be10b547de67'
down_revision = '15cfb1ed6af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
